### ISSUE TITLE
Testing Valuation Pointer

### ISSUE THREAD

**Issue by Hackdom** [TrueBitFoundation/interactive-coin-offerings#18]
## What is it?

After completing #19 

There’s a valuation pointer that calculates the current value of the sale, taking into account the amount of bids committed at each personal cap, dropping calculation of bids with caps below the current value and adding in bids with personal caps above the value, until reaching equilibrium.

### Problem

We need to test that the current contract accurately calculates the overall value as bids are deposited and withdrawn.

### Steps to implement

- [x] Understand accurately how the mechanism works
- [x] Test the pointer in action

**Comment by JGcarv** [comment]
Can we extract this logic into a separate function? I guess it'll make it easier to test it isolated than how currently it is(since it doesn't actually need the bid data, only the sale state).

Also, one could easily make a bit more generic, so that the same function is both used and `sumbitBid` and `withdrawBid`

What do you think?

**Comment by Hackdom** [comment]
Yes 100%. This is definitely something that would move it from a draft to a more production level file.

**Comment by Hackdom** [comment]
This is done in the latest pull request. @JGcarv your work was a God send, I can't thank you enough for what you did there. Be sure to check out the latest.

We can refactor and take advantage of your thoughts here after initial release in a subsequent update.

**Comment by JGcarv** [comment]
Thank you for your help as well!

It's been quite fun testing this :smile:
