### ISSUE TITLE
Add decreasing manual withdrawal amount

### ISSUE THREAD

**Issue by joshuahannan** [TrueBitFoundation/interactive-coin-offerings#5]
The fraction of capital available for withdrawal from each bid gradually decreases over time.  It reaches 0% at the moment of the withdrawal lock.  

Before making changes, a few decisions need to be made:  

- What is the rate that the withdrawal amount decreases?  Linear, exponential, etc.

- What happens to the leftover ETH that is not withdrawn? 

If there are other aspects of this we need to decide on, please leave a comment with a suggestion

**Comment by Hackdom** [comment]
Jason mentioned this is linear.

**Comment by teutsch** [comment]
I think linear is easiest.  The decrease has to be smooth in order to avoid edge case scenarios where one buyer takes an action and others don't have an opportunity to react to it.

**Comment by joshuahannan** [comment]
Does the decrease start at the very beginning of the sale? or partway through? I just seems kind of unfair that they would loose half their bid if they withdraw halfway through the sale. or do they still get to keep the tokens that they bid for but lost because of the penalty?

**Comment by teutsch** [comment]
The decrease begins at the beginning of the sale.  Only the "bonus" is lost on the committed portion.  In essence, a buyer who voluntarily withdraws a bid would receive a price equivalent to a  0% bonus for the remaining, locked-in funds.  It is necessary to have some penalty in place in order to incentivize against signaling of bogus information.
